FROM ubuntu:jammy

LABEL maintainer="Allegro.pl Sp. z o.o. opensource@allegro.pl"
LABEL authors="Allegro.pl Sp. z o.o. and Contributors opensource@allegro.pl"
LABEL description="Helper image to build deb package for Ralph."

ENV DEBEMAIL="root@localhost"
ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL=/bin/bash
ENV EDITOR=/bin/nano
ENV RALPH_DIR=/opt/ralph

RUN apt-get update
RUN apt-get -y install software-properties-common nano
RUN add-apt-repository -y ppa:deadsnakes/ppa && apt-get update
RUN apt-get -y install python3.7 python3.7-dev python3.7-distutil && \
    update-alternatives --install /usr/bin/python3 python3 \
    /usr/bin/python3.7 1 && update-alternatives --config python3
RUN apt-get -y install build-essential git-buildpackage \
    libffi-dev libjpeg-dev libpng-dev libmysqlclient-dev \
    libmysqlclient21 debhelper devscripts equivs dh-virtualenv
RUN apt-get -y install nodejs npm
RUN apt-get autoremove && apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    git config --system --add safe.directory '*'

WORKDIR $RALPH_DIR
ENTRYPOINT ["/bin/bash", "scripts/build_deb_package.sh"]
