name: Publish snapshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'For which branch build snapshot?'
        required: true

jobs:
  publish:

    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
          
      - name: Publish docker snapshot
        env:
          RETRY_COUNT: 3
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
          export RALPH_VERSION=$(shell ./get_version.sh show)
          until [ "$RETRY_COUNT" -le 0 ]
            do
              make publish-docker-snapshot-image && break
              RETRY_COUNT=$((RETRY_COUNT-1))
              echo "==== Publish docker failed. Remaining retries: $RETRY_COUNT ===="
            done
          docker logout
